name: Feature request
description: Request a feature
title: "[Feature]: "
labels: ["Type: Feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a feature. We can't guarantee we will add it, and you should be prepared to help develop it if its something you really want to see.
  - type: textarea
    id: what
    attributes:
      label: What is the feature?
      description: Give us as much detail as you can about the feature you want to see, including links and screenshots of other systems that do it already.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
    validations:
      required: true
